export const MAP_CONFIG = {
  DEFAULT_CENTER: { lat: 37.5665, lng: 126.978 },
  DEFAULT_ZOOM: 16,
  NAVIGATION_ZOOM: 17,
  MARKER_ANIMATION_DURATION: 1000,
  POLYLINE_COLOR: '#4A90D9',
  ALT_POLYLINE_COLOR: '#CCCCCC',
  POLYLINE_WIDTH: 6,
} as const;
